### ISSUE TITLE
No logging in prod env

### ISSUE THREAD

**Issue by gordan-cuic** [superdesk/web-publisher#1128]
I'm having 500 error in browser, but can't analyze anything because Symfony doesn't writ anything to log. Is there any "tweak" or anything I'm missing? Plz help!

This is my `monolog.yaml` (not modified in any way after cloning repo):

```yaml
services:
    monolog.gelf_handler:
        class: Monolog\Handler\GelfHandler
        arguments: ["@gelf.publisher", 100]

    gelf.validator:
        class: Gelf\MessageValidator

    gelf.transport:
        class: Gelf\Transport\UdpTransport
        arguments: ['%env(LOG_DOMAIN)%', '%env(LOG_PORT)%']

    gelf.publisher:
        class: Gelf\Publisher
        arguments: ["@gelf.transport", "@gelf.validator"]

monolog:
    channels:
        - swp_asset_download
        - swp_content_push
        - swp_image_conversion
        - swp_rule
        - swp_validators
    handlers:
        console:
            type:  console
        custom_channels:
            type: fingers_crossed
            action_level: debug
            handler: grouped
            channels:
                - swp_content_push
                - swp_image_conversion
                - swp_asset_download
                - swp_rule
                - swp_validators
        app:
            type: fingers_crossed
            action_level: error
            handler: grouped
            channels:
                - app
            excluded_http_codes: [404]
        grouped:
            type: whatfailuregroup
            members: [streamed, gelf]
        streamed:
            type:  rotating_file
            max_files: 7
        gelf:
            type: service
            id: monolog.gelf_handler
            include_stacktraces: true
```
