### ISSUE TITLE
[WIP] [Proposal] Template containers system

### ISSUE THREAD

**Issue by ahilles107** [superdesk/web-publisher#37]
Container - special twig block in templates witch can contain widgets (or default content). Container have his representation in database and provides api to change it - so it can be modified without changes in template file. Container is registered on first render or theme scanning. 

Example code in template:
```twig 
{{ container 'container_name' { 
    'width': 400, 
    'height': 500, 
    'styles': 'border: solid 1px red', 
    'class': 'css_class_name', 
    'data': {'custom-key': value}
}}}
Here is default content - if there is no widgets attached to container. 
{{ endcontainer }}
```
it would render smth like that
```html
<div id="container_id" class="css_class_name" style="width: 400px; height: 500px; border: solid 1px red" data-custom-key="value">
Here is default content - if there is no widgets attached to container. 
</div>
```
Container Entity:
```yml 
SWP\TemplateEngineBundle\Model\Container:
    type: entity
    table: null
    repositoryClass: SWP\TemplateEngineBundle\Repository\ContainerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: integer
        width:
            type: integer
        height:
            type: integer
        styles:
            type: text
        class:
            type: string
            length: 255
        visible:
            type: boolean
    oneToMany:
        data:
            targetEntity: SWP\TemplateEngineBundle\Model\ContainerData
            mappedBy: container
```
Container Data Entity:
```yml 
SWP\TemplateEngineBundle\Model\ContainerData:
    type: entity
    table: null
    repositoryClass: SWP\TemplateEngineBundle\Repository\ContainerDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        key:
            type: string
            length: 255
        value:
            type: string
            length: 255
    manyToOne:
        container:
            targetEntity: SWP\TemplateEngineBundle\Model\Container
            joinColumn:
                name: container_id
                referencedColumnName: id
```

Container object (used by twig)

```php

<?php

namespace SWP\TemplateEngine\Container;

class Container
{
   private $containerModel;

   /**
    * Renders container (div) with all parameters from $containerModel object, 
    * also foreach on all widgets in Container and renders them
    */
    private function render(){};
}
```
We need provide REST API to control containers

Method | Endpoint | Description
------------ | ------------- | ----------------
|POST  | /api/container/{id} | update container |
|GET |  /api/container/{id} | get container |
|LINK/UNLINK |  /api/container/{id}/widget | link unlink widgets to container |
